### ISSUE TITLE
Is there utility to having UniformGrid and MultiGrid defined as different structs?

### ISSUE THREAD

**Issue by ajgoza** [NUFgroup/IBPM.jl#3]

**Comment by jcallaham** [comment]
Basically up to you.  I did this for debugging as I was implementing the multigrid method since several of the methods are much more straightforward on a single grid, but at the moment there's no reason you wouldn't use multigrid.

Would having existing multiple dispatch examples be useful in the future for something like AMR?  If not, I see no reason to keep UniformGrid now that MultiGrid has been tested.

**Comment by ajgoza** [comment]
Definitely makes sense to me that it was useful for debugging! My current (very early stage) vision for AMR/grid non uniformity is to leverage quadtree data structures, which I think will be pretty structurally different from the current uniform/multi grid stuff. So my instinct is we can just combine and eventual changes to gridding will just use fundamentally different types. But I'm happy either way!

**Comment by jcallaham** [comment]
Agreed to cut this.. double check coarsify call in advance

**Comment by jcallaham** [comment]
Removed UniformGrid and associated functions.  Also checked to make sure we get the same results and runtime by just using a MultiGrid with `mg=1`
